CREATE DATABASE db_creditos;
USE db_creditos;

CREATE TABLE productos
(
	ID_PRODUCTO          INTEGER PRIMARY KEY AUTO_INCREMENT,
	SKU                  INT(12) NOT NULL,
	NOMBRE_PRODUCTO      VARCHAR(50) NOT NULL,
	DESCRIPCION          VARCHAR(250) NOT NULL,
	PRECIO               FLOAT NOT NULL DEFAULT 0
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;


CREATE TABLE plazos
(
	ID_PLAZO            INTEGER PRIMARY KEY AUTO_INCREMENT,
	PLAZO                VARCHAR(50) NOT NULL,
	TASA_NORMAL          FLOAT NOT NULL,
	TASA_PUNTUAL         FLOAT NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;


CREATE TABLE cotizacion
(
	ID_COTIZACIÓN        INTEGER PRIMARY KEY AUTO_INCREMENT,
	ID_PRODUCTO          INTEGER NOT NULL,
	ID_PLAZO             INTEGER NULL,
	ABONO_SEMANAL        FLOAT NOT NULL,
	ABONO_PUNTUAL        FLOAT NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;



ALTER TABLE cotizacion
ADD FOREIGN KEY FK_PRODUCTOS_TO_COTIZACION (ID_PRODUCTO) REFERENCES productos (ID_PRODUCTO);

ALTER TABLE cotizacion
ADD FOREIGN KEY FK_PLAZOS_TO_COTIZACION (ID_PLAZO) REFERENCES plazos (ID_PLAZO);





